users: []

r_pose:
  x: 0.7
  y: 0.9
  z: 0.0
  th: -0.5

rooms:
  bed:
    x: -1.4
    y: 1
    z: 0
    th: 0.4
  door:
    x: 3.1
    y: 0.9
    z: 0.0
    th: -2.3
  box:
    x: 0.7
    y: 0.9
    z: 0.0
    th: -0.5
  bathroom:
    x: 2.3
    y: 0.3
    z: 0.0
    th: -1
  living:
    x: -0.4
    y: -2.35
    z: 0.0
    th: 0.65
  kitchen:
    x: 6.5
    y: -3.5
    z: 0.0
    th: 1
